package me.datafox.dfxengine.text.api;

import me.datafox.dfxengine.dependencies.Dependency;
import me.datafox.dfxengine.dependencies.Dependent;

/**
 * A text value that can depend on other text values. May or may not be generated. If the value is generated
 * ({@link #isGenerated()} returns {@code true}), a new version can be generated by calling {@link #generate()},
 * otherwise calling the method does nothing. Any calls to {@link #generate()} must be forwarded to all other texts
 * this text depends on, and if any of the texts this text depends on is generated, this text is also generated.
 *
 * @author datafox
 */
public interface Text extends CharSequence, Dependency, Dependent {
    /**
     * @return {@code true} if this text or any of the texts this text depends on is generated
     */
    boolean isGenerated();

    /**
     * Generates a new iteration of this text if {@link #isGenerated()} is {@code true}, otherwise does nothing.
     */
    void generate();
}
